name: quark-portal

x-common:
  db: &db-environment
    # Postgres credentials
    POSTGRES_PASSWORD: &db-password "CHANGE_ME_PLEASE!"
    POSTGRES_USER: "quark"
    POSTGRES_DB: "portal"

  app: &app-environment
    # Core app
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_URL: "https://example.com"
    APP_TIMEZONE: "UTC"
    APP_LOCALE: "en"
    APP_FALLBACK_LOCALE: "en"
    LOG_CHANNEL: "stack"
    LOG_LEVEL: "debug"

    # Laravel drivers (no Redis)
    SESSION_DRIVER: "database"
    QUEUE_CONNECTION: "database"
    CACHE_STORE: "database"

    # Database (matches db service)
    DB_CONNECTION: "pgsql"
    DB_HOST: "db"
    DB_PORT: "5432"
    DB_DATABASE: "portal"
    DB_USERNAME: "quark"
    # DB_PASSWORD is injected via *db-password below

    # Optional app-specific vars
    PTERO_URL: "https://panel.example.com"
    PTERO_APP_KEY: "ptero_..."
    CASHIER_CURRENCY: "czk"

  mail: &mail-environment
    MAIL_MAILER: "smtp"
    MAIL_HOST: "smtp.seznam.cz"
    MAIL_PORT: "465"
    MAIL_USERNAME: "noreply@example.com"
    MAIL_PASSWORD: "ChangeMe123!"
    MAIL_ENCRYPTION: "ssl"
    MAIL_FROM_ADDRESS: "noreply@example.com"
    MAIL_FROM_NAME: "Quark Portal"

services:
  db:
    image: postgres:15
    container_name: quark-portal-db
    restart: always
    environment:
      <<: *db-environment
    volumes:
      - quark_db_data:/var/lib/postgresql/data
    # Optional: expose to host tools (pgAdmin/psql)
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quark -d portal"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    # Option A: use your published image on GHCR
    image: ghcr.io/jsemolik/quark-portal:latest
    # Option B: build locally instead of pulling:
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: quark-portal-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8670:80" # Apache inside container listens on 80
    environment:
      <<: [*app-environment, *mail-environment]
      DB_PASSWORD: *db-password
      # Set APP_KEY here if your image/entrypoint doesn't generate it:
      # APP_KEY: "base64:..."
    volumes:
      # Persist Laravel runtime data outside the image
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    # Optional healthcheck for app
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

volumes:
  quark_db_data:
