<?php

// config/games.php
return [
    'minecraft' => [
        'nest_id' => 1,
        'variants' => [
            'paper' => [
                'label' => 'Paper',
                'egg_id' => 2,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}',
                'env' => [
                    'MINECRAFT_VERSION' => 'latest',
                    'SERVER_JARFILE' => 'paper.jar',
                    'DL_PATH' => '',
                    'BUILD_NUMBER' => 'latest',
                ],
            ],
            'vanilla' => [
                'label' => 'Vanilla',
                'egg_id' => 4,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -jar {{SERVER_JARFILE}}',
                'env' => [
                    'SERVER_JARFILE' => 'server.jar',
                    'VANILLA_VERSION' => 'latest',
                ],
            ],
            'purpur' => [
                'label' => 'Purpur',
                'egg_id' => 1,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java --add-modules=jdk.incubator.vector -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}',
                'env' => [
                    'MINECRAFT_VERSION' => 'latest',
                    'SERVER_JARFILE' => 'purpur.jar',
                    'BUILD_NUMBER' => 'latest',
                ],
            ],
            'bungeecord' => [
                'label' => 'Bungeecord',
                'egg_id' => 3,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -jar {{SERVER_JARFILE}}',
                'env' => [
                    'BUNGEE_VERSION' => 'latest',
                    'SERVER_JARFILE' => 'bungeecord.jar',
                ],
            ],
            'fabric' => [
                'label' => 'Fabric',
                'egg_id' => 5,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -jar {{SERVER_JARFILE}}',
                'env' => [
                    'MINECRAFT_VERSION' => 'latest',
                    'SERVER_JARFILE' => 'fabric.jar',
                    'FABRIC_VERSION' => 'latest',
                    'FABRIC_INSTALLER_VERSION' => 'latest',
                ],
            ],
            'sponge' => [
                'label' => 'Sponge (SpongeVanilla)',
                'egg_id' => 6,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -jar {{SERVER_JARFILE}}',
                'env' => [
                    'SPONGE_VERSION' => '1.12.2-7.3.0',
                    'SERVER_JARFILE' => 'spongevanilla.jar',
                ],
            ],
            'forge' => [
                'label' => 'Forge',
                'egg_id' => 7,
                'docker_image' => 'ghcr.io/pterodactyl/yolks:java_21',
                'startup' => 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[  ! -f unix_args.txt ]] && printf %s "-jar {{SERVER_JARFILE}}" || printf %s "@unix_args.txt" )',
                'env' => [
                    'SERVER_JARFILE' => 'server.jar',
                    'MC_VERSION' => 'latest',
                    'BUILD_TYPE' => 'recommended',
                    'FORGE_VERSION' => '',
                ],
            ],
        ],
        'requires_db' => false,
    ],

    'counter_strike' => [
        'nest_id' => 2,
        'variants' => [
            'csgo' => [
                'label' => 'CS:GO',
                'egg_id' => 22,
                'docker_image' => 'ghcr.io/pterodactyl/games:source',
                'startup' => './srcds_run -game csgo -console -port {{SERVER_PORT}} +ip 0.0.0.0 +map {{SRCDS_MAP}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}}',
                'env' => [
                    'SRCDS_MAP' => 'de_dust2',
                    'STEAM_ACC' => '00000000000000000000000000000000',
                    'SRCDS_APPID' => '740',
                ],
            ],
            'cs2' => [
                'label' => 'CS2',
                'egg_id' => 23,
                'docker_image' => 'docker.io/sples1/k4ryuu-cs2:latest',
                'startup' => './game/cs2.sh -dedicated +ip 0.0.0.0 -port {{SERVER_PORT}} +map {{SRCDS_MAP}} -maxplayers {{SRCDS_MAXPLAYERS}} +sv_setsteamaccount {{STEAM_ACC}}',
                'env' => [
                    'SRCDS_MAP' => 'de_dust2',
                    'SRCDS_APPID' => '730',
                    'SRCDS_MAXPLAYERS' => '64',
                    'SRCDS_STOP_UPDATE' => '0',
                    'SRCDS_VALIDATE' => '0',
                    'STEAM_ACC' => '',
                ],
            ],
        ],
        'requires_db' => false,
    ],

    'rust' => [
        'nest_id' => 2,
        'variants' => [
            'rust' => [
                'label' => 'Rust',
                'egg_id' => 21,
                'docker_image' => 'ghcr.io/pterodactyl/games:rust',
                'startup' => './RustDedicated -batchmode +server.port {{SERVER_PORT}} +server.queryport {{QUERY_PORT}} +server.identity "rust" +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname \"{{HOSTNAME}}\" +server.level \"{{LEVEL}}\" +server.description \"{{DESCRIPTION}}\" +server.url \"{{SERVER_URL}}\" +server.headerimage \"{{SERVER_IMG}}\" +server.logoimage \"{{SERVER_LOGO}}\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \"{{RCON_PASS}}\" +server.saveinterval {{SAVEINTERVAL}} +app.port {{APP_PORT}}  $( [ -z ${MAP_URL} ] && printf %s "+server.worldsize \"{{WORLD_SIZE}}\" +server.seed \"{{WORLD_SEED}}\"" || printf %s "+server.levelurl {{MAP_URL}}" ) {{ADDITIONAL_ARGS}}',
                'env' => [
                    'HOSTNAME' => 'A QuarkHost.io Rust Server!',
                    'FRAMEWORK' => 'vanilla',
                    'LEVEL' => 'Procedural Map',
                    'DESCRIPTION' => 'Hosted on quarkhost.io | Get yours too!',
                    'SERVER_URL' => 'https://quarkhost.io',
                    'WORLD_SIZE' => '3000',
                    'WORLD_SEED' => '',
                    'MAX_PLAYERS' => '40',
                    'SERVER_IMG' => '',
                    'QUERY_PORT' => '27017',
                    'RCON_PORT' => '28016',
                    'RCON_PASS' => '123456789',
                    'SAVEINTERVAL' => '60 ',
                    'ADDITIONAL_ARGS' => '',
                    'APP_PORT' => '28082',
                    'SERVER_LOGO' => '',
                    'MAP_URL' => '',
                ],
            ],
        ],
        'requires_db' => false,
    ],
    'ark' => [
        'nest_id' => 2,
        'variants' => [
            'ark' => [
                'label' => 'ARK: Survival Ascended',
                'egg_id' => 11,
                'docker_image' => 'quay.io/parkervcp/pterodactyl-images:debian_source',
                'startup' => 'rmv() { echo -e "stopping server"; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c saveworld && rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c DoExit; }; trap rmv 15; cd ShooterGame/Binaries/Linux && ./ShooterGameServer {{SERVER_MAP}}?listen?SessionName="{{SESSION_NAME}}"?ServerPassword={{ARK_PASSWORD}}?ServerAdminPassword={{ARK_ADMIN_PASSWORD}}?Port={{SERVER_PORT}}?RCONPort={{RCON_PORT}}?QueryPort={{QUERY_PORT}}?RCONEnabled=True$( [ "$BATTLE_EYE" == "1" ] || printf %s \' -NoBattlEye\' ) -server {{ARGS}} -log & until echo "waiting for rcon connection..."; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD}; do sleep 5; done',
                'env' => [
                    'ARK_PASSWORD' => '',
                    'ARK_ADMIN_PASSWORD' => 'PleaseChangeMe',
                    'SERVER_MAP' => 'TheIsland',
                    'SESSION_NAME' => '{{SERVER_NAME}}',
                    'RCON_PORT' => '27020',
                    'QUERY_PORT' => '27015',
                    'AUTO_UPDATE' => '0',
                    'BATTLE_EYE' => '1',
                    'SRCDS_APPID' => '376030',
                    'ARGS' => '',
                ],
            ],
        ],
        'requires_db' => false,
    ],
    'gmod' => [
        'nest_id' => 2,
        'variants' => [
            'gmod' => [
                'label' => "Garry's Mod",
                'egg_id' => 13,
                'docker_image' => 'ghcr.io/pterodactyl/games:source',
                'startup' => './srcds_run -game garrysmod -console -port {{SERVER_PORT}} +ip 0.0.0.0 +host_workshop_collection {{WORKSHOP_ID}} +map {{SRCDS_MAP}} +gamemode {{GAMEMODE}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}} +maxplayers {{MAX_PLAYERS}}  -tickrate {{TICKRATE}}  $( [ "$LUA_REFRESH" == "1" ] || printf %s \'-disableluarefresh\' )',
                'env' => [
                    'SRCDS_MAP' => 'gm_flatgrass',
                    'STEAM_ACC' => '',
                    'SRCDS_APPID' => '4020',
                    'WORKSHOP_ID' => '',
                    'GAMEMODE' => 'sandbox',
                    'MAX_PLAYERS' => '32',
                    'TICKRATE' => '22',
                    'LUA_REFRESH' => '0',
                ],
            ],
        ],
        'requires_db' => false,
    ],

    // VALHEIM \\

    'valheim' => [
        'nest_id' => 7,
        'variants' => [
            'valheim' => [
                'label' => 'Valheim Vanilla',
                'egg_id' => 26,
                'docker_image' => 'ghcr.io/parkervcp/games:valheim',
                'startup' => './valheim_server.x86_64 -nographics -batchmode -name "{{SERVER_NAME}}" -port {{SERVER_PORT}} -world "{{WORLD}}" -password "{{PASSWORD}}" -public {{PUBLIC_SERVER}} -saveinterval {{BACKUP_INTERVAL}} -backups {{BACKUP_COUNT}} -backupshort {{BACKUP_SHORTTIME}} -backuplong {{BACKUP_LONGTIME}} $( [[ {{ENABLE_CROSSPLAY}} -eq 1 ]] && echo " -crossplay ") > >(sed -uE "{{CONSOLE_FILTER}}") & trap "{{STOP}}" 15; wait $!',
                'env' => [
                    'SERVER_NAME' => 'A Valheim Server! | quarkhost.io',
                    'PASSWORD' => 'secret',
                    'WORLD' => 'Dedicated',
                    'PUBLIC_SERVER' => '1',
                    'SRCDS_APPID' => '896660',
                    'LD_LIBRARY_PATH' => './linux64',
                    'STOP' => 'kill -2 $!; wait;',
                    'AUTO_UPDATE' => '1',
                    'ENABLE_CROSSPLAY' => '1',
                    'BACKUP_INTERVAL' => '1800',
                    'BACKUP_COUNT' => '4',
                    'BACKUP_SHORTTIME' => '7200',
                    'BACKUP_LONGTIME' => '43200',
                    'SRCDS_BETAID' => '',
                    'SRCDS_BETAPASS' => '',
                    'CONSOLE_FILTER' => '/^\(Filename:.*Line:[[:space:]]+[[:digit:]]+\)$/d; /^([[:space:]]+)?$/d',

                ],
            ],
            'valheim_bepinex' => [
                'label' => 'Valheim BepINex',
                'egg_id' => 27,
                'docker_image' => 'ghcr.io/parkervcp/games:valheim',
                'startup' => 'export DOORSTOP_ENABLE=TRUE; export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll; export LD_LIBRARY_PATH="./doorstop_libs:$LD_LIBRARY_PATH"; export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"; export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH="./linux64:$LD_LIBRARY_PATH"; export SteamAppId=892970; export LD_LIBRARY_PATH=$templdpath; ./valheim_server.x86_64 -nographics -batchmode -name "{{SERVER_NAME}}" -port {{SERVER_PORT}} -world "{{WORLD}}" -password "{{PASSWORD}}" -public {{PUBLIC_SERVER}} -saveinterval {{BACKUP_INTERVAL}} -backups {{BACKUP_COUNT}} -backupshort {{BACKUP_SHORTTIME}} -backuplong {{BACKUP_LONGTIME}} $( [[ {{ENABLE_CROSSPLAY}} -eq 1 ]] && echo " -crossplay ") > >(sed -uE "{{CONSOLE_FILTER}}") & trap "{{STOP}}" 15; wait $!',
                'env' => [
                    'SERVER_NAME' => 'A BepINex Valheim Server! | quarkhost.io',
                    'PASSWORD' => 'secret',
                    'WORLD' => 'Dedicated',
                    'PUBLIC_SERVER' => '1',
                    'SRCDS_APPID' => '896660',
                    'LD_LIBRARY_PATH' => './linux64',
                    'STOP' => 'kill -2 $!; wait;',
                    'AUTO_UPDATE' => '1',
                    'ENABLE_CROSSPLAY' => '0',
                    'BACKUP_INTERVAL' => '1800',
                    'BACKUP_COUNT' => '4',
                    'BACKUP_SHORTTIME' => '7200',
                    'BACKUP_LONGTIME' => '43200',
                    'SRCDS_BETAID' => '',
                    'SRCDS_BETAPASS' => '',
                    'CONSOLE_FILTER' => '/^\(Filename:.*Line:[[:space:]]+[[:digit:]]+\)$/d; /^([[:space:]]+)?$/d',
                    'V_MODPACK' => '',
                ],
            ],
            'valheim_plus_mod' => [
                'label' => 'Valheim Plus Mod',
                'egg_id' => 28,
                'docker_image' => 'ghcr.io/parkervcp/games:valheim',
                'startup' => 'export DOORSTOP_ENABLE=TRUE; export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll; export DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib; export LD_LIBRARY_PATH="./doorstop_libs:$LD_LIBRARY_PATH"; export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"; export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH="./linux64:$LD_LIBRARY_PATH"; export SteamAppId=892970; export LD_LIBRARY_PATH=$templdpath; ./valheim_server.x86_64 -nographics -batchmode -name "{{SERVER_NAME}}" -port {{SERVER_PORT}} -world "{{WORLD}}" -password "{{PASSWORD}}" -public {{PUBLIC_SERVER}} -saveinterval {{BACKUP_INTERVAL}} -backups {{BACKUP_COUNT}} -backupshort {{BACKUP_SHORTTIME}} -backuplong {{BACKUP_LONGTIME}} $( [[ {{ENABLE_CROSSPLAY}} -eq 1 ]] && echo " -crossplay ") > >(sed -uE "{{CONSOLE_FILTER}}") & trap "{{STOP}}" 15; wait $!',
                'env' => [
                    'SERVER_NAME' => 'A BepINex Valheim Server! | quarkhost.io',
                    'PASSWORD' => 'secret',
                    'WORLD' => 'Dedicated',
                    'PUBLIC_SERVER' => '1',
                    'SRCDS_APPID' => '896660',
                    'LD_LIBRARY_PATH' => './linux64',
                    'GITHUB_PACKAGE' => 'Grantapher/ValheimPlus',
                    'VERSION' => 'latest',
                    'MATCH' => 'UnixServer.zip',
                    'FILTER' => '/^\(Filename:.*Line:[[:space:]]+[[:digit:]]+\)$/d; /^([[:space:]]+)?$/d',
                    'STOP' => 'kill -2 $!; wait;',
                    'AUTO_UPDATE' => '1',
                    'ENABLE_CROSSPLAY' => '0',
                    'BACKUP_INTERVAL' => '1800',
                    'BACKUP_COUNT' => '4',
                    'BACKUP_SHORTTIME' => '7200',
                    'BACKUP_LONGTIME' => '43200',
                    'SRCDS_BETAID' => '',
                    'SRCDS_BETAPASS' => '',
                    'CONSOLE_FILTER' => '/^\(Filename:.*Line:[[:space:]]+[[:digit:]]+\)$/d; /^([[:space:]]+)?$/d',
                    'V_MODPACK' => '',
                ],
            ],
        ],
        'requires_db' => false,
    ],
    'template' => [
        'nest_id' => 1,
        'variants' => [
            'variant1' => [
                'label' => "Label",
                'egg_id' => 1,
                'docker_image' => 'dockerimage',
                'startup' => 'startup',
                'env' => [
                    'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                    // 'template' => 'template',
                ],
            ],
        ],
        'requires_db' => false,
    ],

    // TRUCKING SIMULATORS \\

    'trucking_simulators' => [
        'nest_id' => 6,
        'variants' => [
            'euro_truck_2_sim' => [
                'label' => "Euro Truck Simulator 2",
                'egg_id' => 24,
                'docker_image' => 'ghcr.io/parkervcp/steamcmd:debian',
                'startup' => './bin/linux_x64/eurotrucks2_server',
                'env' => [
                    'AUTO_UPDATE' => '1',
                    'SRCDS_APPID' => '1948160',
                    'QUERY_PORT' => '27016',
                    'STEAM_TOKEN' => '',
                    'LOBBY_NAME' => 'An awesome ETS2 server! | quarkhost.io',
                ],
            ],
            'american_truck_sim' => [
                'label' => "American Truck Simulator",
                'egg_id' => 24,
                'docker_image' => 'ghcr.io/parkervcp/steamcmd:debian',
                'startup' => './bin/linux_x64/amtrucks_server',
                'env' => [
                    'AUTO_UPDATE' => '1',
                    'SRCDS_APPID' => '2239530',
                    'QUERY_PORT' => '27016',
                    'STEAM_TOKEN' => '',
                    'LOBBY_NAME' => 'An awesome ATS server! | quarkhost.io',
                ],
            ],
        ],
        'requires_db' => false,
    ],

    // TERRARIA \\

    'terraria' => [
        'nest_id' => 8,
        'variants' => [
            'terraria_vanilla' => [
                'label' => "Terraria Vanilla",
                'egg_id' => 29,
                'docker_image' => 'ghcr.io/parkervcp/yolks:debian',
                'startup' => './TerrariaServer.bin.x86_64 -config serverconfig.txt',
                'env' => [
                    'TERRARIA_VERSION' => 'latest',
                    'WORLD_NAME' => 'world',
                    'MAX_PLAYERS' => '8',
                    'WORLD_SIZE' => '1',
                    'WORLD_DIFFICULTY' => '3',
                    'SERVER_MOTD' => 'Welcome! | quarkhost.io',
                    'WORLD_SEED' => '',
                    'PASSWORD' => '',
                    'NPCSTREAM' => '0',
                ],
            ],
            'terraria_tmodloader' => [
                'label' => "Terraria tModloader",
                'egg_id' => 30,
                'docker_image' => 'ghcr.io/parkervcp/yolks:dotnet_6',
                'startup' => './tModLoaderServer -ip 0.0.0.0 -port {{SERVER_PORT}} -maxplayers {{MAX_PLAYERS}} -password "{{SERVER_PASSWORD}}" -motd "{{MOTD}}" -lang {{LANGUAGE}} -world ~/saves/Worlds/{{WORLD_NAME}}.wld -worldname {{WORLD_NAME}} -autocreate {{WORLD_SIZE}} -config serverconfig.txt -savedirectory ~/ -tmlsavedirectory ~/saves -modpath ~/mods',
                'env' => [
                    'WORLD_NAME' => 'world',
                    'MAX_PLAYERS' => '8',
                    'WORLD_SIZE' => '1',
                    'VERSION' => 'latest',
                    'GITHUB_USER' => '',
                    'GITHUB_OAUTH_TOKEN' => '',
                    'DIFFICULTY' => '0',
                    'MOTD' => 'Welcome! | quarkhost.io',
                    'LANGUAGE' => '1',
                ],
            ],
            'terraria_tshock' => [
                'label' => "Terraria tshock",
                'egg_id' => 30,
                'docker_image' => 'ghcr.io/parkervcp/yolks:dotnet_6',
                'startup' => './TShock.Server -ip 0.0.0.0 -port {{SERVER_PORT}} -maxplayers {{MAX_PLAYERS}} -world {{WORLD_NAME}}.wld -autocreate {{WORLD_SIZE}}',
                'env' => [
                    'WORLD_NAME' => 'world',
                    'MAX_PLAYERS' => '8',
                    'WORLD_SIZE' => '1',
                    'VERSION' => 'latest',
                    'GITHUB_USER' => '',
                    'GITHUB_OAUTH_TOKEN' => '',
                    'DIFFICULTY' => '0',
                    'MOTD' => 'Welcome! | quarkhost.io',
                    'LANGUAGE' => '1',
                ],
            ],
        ],
        'requires_db' => false,
    ],
];
