<?php

return [
    'currency' => env('BILLING_CURRENCY', 'czk'),

    'plans' => [
        [
            'key' => 'core',
            'name' => 'Core',
            'description' => '4GB DDR4 RAM',
            'cpu' => 'AMD Ryzen™ 7 5700',
            'vcores' => '4 vCores @ ~4.2 GHz',
            'ram' => '4GB DDR4 RAM',
            'storage' => 'Unlimited NVMe Storage',
            'backups' => '5 Free Backups',
            'ports' => '12 Port Allocations',
            'popular' => false,
            'intervals' => [
                'monthly' => 10000,
                'quarterly' => 28500,
                'semi_annual' => 54000,
                'annual' => 102000,
            ],
        ],
        [
            'key' => 'boost',
            'name' => 'Boost',
            'description' => '6GB DDR4 RAM',
            'cpu' => 'AMD Ryzen™ 7 5700',
            'vcores' => '4 vCores @ ~4.2 GHz',
            'ram' => '6GB DDR4 RAM',
            'storage' => 'Unlimited NVMe Storage',
            'backups' => '5 Free Backups',
            'ports' => '12 Port Allocations',
            'popular' => false,
            'intervals' => [
                'monthly' => 15000,
                'quarterly' => 42750,
                'semi_annual' => 81000,
                'annual' => 153000,
            ],
        ],
        [
            'key' => 'power',
            'name' => 'Power',
            'description' => '8GB DDR4 RAM',
            'cpu' => 'AMD Ryzen™ 7 5700',
            'vcores' => '4 vCores @ ~4.2 GHz',
            'ram' => '8GB DDR4 RAM',
            'storage' => 'Unlimited NVMe Storage',
            'backups' => '5 Free Backups',
            'ports' => '12 Port Allocations',
            'popular' => true,
            'intervals' => [
                'monthly' => 20000,
                'quarterly' => 57000,
                'semi_annual' => 108000,
                'annual' => 204000,
            ],
        ],
        [
            'key' => 'extreme',
            'name' => 'Extreme',
            'description' => '10GB DDR4 RAM',
            'cpu' => 'AMD Ryzen™ 7 5700',
            'vcores' => '4 vCores @ ~4.2 GHz',
            'ram' => '10GB DDR4 RAM',
            'storage' => 'Unlimited NVMe Storage',
            'backups' => '5 Free Backups',
            'ports' => '12 Port Allocations',
            'popular' => false,
            'intervals' => [
                'monthly' => 25000,
                'quarterly' => 71250,
                'semi_annual' => 135000,
                'annual' => 255000,
            ],
        ],
    ],
];
